### ISSUE TITLE
Revisit architecture decision reports

### ISSUE THREAD

**Issue by kasperisager** [Siteimprove/alfa#291]
The last time an ADR was added was in March, 2019: 3b4329a96ab0c180fe6027cfb92be8a9270406b8. Since then, several additional architecture decisions have been made, notably as part of #165. #172 was opened as a reminder to write ADRs for that particular set of changes, but this has not yet manifested due to other priorities. I'd like for us to sit down at some point and come up with a list of decisions that we feel are _important_ to document. Not just for our own sake, but for the sake of future colleagues and collaborators who wish to understand the fundamental decisions that brought Alfa to where it's currently at, which is the whole point of the ADRs.

Off the top of my head, the following things come to mind:

- [x] No external dependencies
- [x] Functional code, no external/hidden side effect
- [x] No stray exports (only namespaces)
- [x] The introduction of DOM parent pointers in #165 and later the adjustments to how they were handled in #283.
- [x] The introduction of the `Option<T>` type in #165. Why not `T | null` or `T | undefined` combined with the optional chaining operator, `?.`, and the nullish coalescing operator, `??`?
- [x] The introduction of the `Future<T>` type in #165. Why not `Promise<T>`?
- [x] The introduction of the `Result<T, E>` type in #165. Why not exceptions?
- [x] Side-effect free questions
- [x] The introduction of the trilean logic in #174. Why was boolean logic insufficient?
- [x] The introduction of the `@siteimprove/alfa-command` package in #265. Why not any of the countless other CLI libraries for Node.js?
- [x] (extended) diagnostics
- [x] enriched questions: rhetorical, optional, with diagnostic
